#! /bin/bash

package="knife"
version="1.0-1"
source_url="https://github.com/airstruck/knife"
name="$package-$version"
rm -rf rocks/*
echo "
=== Building rocks ===
"
luarocks build --local rockspec/$name.rockspec
echo "
=== Packing rocks ===
"
luarocks pack --local $package
luarocks remove --local $package
mv *.rock rocks
cp rockspec/$name.rockspec rocks/
echo "
=== Making manifest ===
"
luarocks-admin make-manifest rocks/
mkdir rocks/$package
echo "<!doctype html>
<html><head><title>Redirecting...</title>
<meta http-equiv='refresh' content='2; url=$source_url'>
</head><body>
<code>Redirecting to <a href='$source_url'>$source_url</a></code>
</body></html>" > rocks/$package/index.html
echo "
=== Running tests ===
"
lua5.1 -lluacov ./knife/test.lua ./spec/*; luacov; rm luacov.stats.out
tail luacov.report.out
